version: '3.7'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      # # POSTGRES_DB: mydb
      # # POSTGRES_USER: myusername
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/notes-back-07
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PG_PASSWORD: password

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local